config/routes.rb
Rails.application.routes.draw do
  root "rooms#index"
  resources :rooms do
    resources :messages
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  after_commit do
    broadcast_append_to "room_#{room.id}"
  end




  private

  def broadcast_append_to_room
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController


    def create
        @message = current_user.messages.build(message_params)
        @message.room_id = params[:room_id]
        @message.save
    end

    private
    def message_params
        params.require(:message).permit(:body)
    end
end 

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
    @messages = @room.messages

  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<div class="row">
  <div class="col-12">
    <%= simple_form_for([@room, Message.new], data: { action: "turbo:submit-end->messages#resetForm", messages_target: "input_form" }) do |f|%>
      <div class="input-group">
        <%= f.input :body,
         label: false,
          input_html: { placeholder: "Enter a message to send" }, wrapper_html: { class: 'form-control' },
           class: 'form-control' %>
        <%= f.submit "Send",  class: 'btn-primary btn w-100 btn-block'%>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<%= turbo_frame_tag(dom_id(message)) do%>
  <div class="row">
    <h4><%= "#{message.body}"%></h4>
    <small class="text-sm text-muted ">   <%= "#{message.user.email.split('@')[0].capitalize}" %> - <%= time_ago_in_words(message.created_at) + ' ago'%> </small>
  </div>
<% end %>

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div class="row">
  <div class="col-lg-10 ">
    <div id="<%= dom_id room %>" data-controller="messages">
      <%= turbo_stream_from dom_id(room) %>
      <nav class="navbar bg-light">
        <div class="container-fluid d-flex">
          <a class="navbar-brand fw-bold h1" ><%= room.name %></a>
          <a class="navbar-brand fw-thin"><%= room.messages.count == 0 ? "No New Message" : pluralize(room.messages.count, 'message') %></a>
        </div>
      </nav>
      <div id="messages" data-messages-target="container">
        <% @messages&.each do |message|%>
          <%= render "messages/message", message: message, user: current_user %>
        <% end %>
      </div>
      <div id="new_message">
        <%= render 'messages/form', room: room%>
      </div>
    </div>
  </div>
  <div class="col-lg-2">
    <%= render 'rooms/sidebar'%>
  </div>
</div>

app/views/rooms/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 bg-light" style="height: auto;">
  <a href="/" class="d-block mt-5 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
    <svg class="bi" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    <span class="visually-hidden">Icon-only</span>
  </a>
  <ul class="nav nav-pills nav-flush flex-column mb-auto text-center">
    <li class="nav-item">
      <h2>
        <i class="bi bi-envelope"></i>
        <%= @room.name %></h2>
      <p class="text-muted">Created <%= time_ago_in_words(@room.created_at)+ ' ago' %></p>
    </a>
  </li>
  <li class="mt-2">
    <%= button_to 'Delete Room', room_path(@room), method: :delete, class: 'btn btn-danger btn-block'%>
  </li>
  <li class="mt-3">
    <%= link_to 'Edit Room', edit_room_path(@room), class: 'btn btn-success btn-block'%>
  </li>
  <li class="mt-3">
    <%= link_to 'Return Home', root_path, class: 'btn btn-success btn-block'%>
  </li>
  <li class="mt-5">
    <i class="bi bi-person"></i>
    <p class="text-muted">
      Users are responsible for safeguarding their personal information and refraining from sharing sensitive data, such as contact details or financial information, within the app. We are committed to protecting your privacy; 
    </p>
  </li>
</ul>
</div>

app/views/rooms/edit.html.erb
<div class="container mt-5">
  <div class="card p-4">
    <h1>Editing room</h1>
    <%= render "form", room: @room %>
    <br>
    <div>
      <%= link_to "Show this room", @room %> |
      <%= link_to "Back to rooms", rooms_path %>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <p style="color: green"><%= notice %></p>
      <div class="title d-flex justify-content-between">
        <div class="title-main">
          <h1 class="display-5 fw-bold">
            <i class="bi bi-house"></i> Rooms </h1>
        </div>
        <div class="user-info d-flex">
          <p class="mt-2">Logged in as: <%= current_user.email %>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete , class:'btn btn-danger btn-sm mt-1 mx-3'%>
          </p>
        </div>
      </div>
      <div class="container">
        <div id="rooms" class="mt-3">
          <% if @rooms.count > 0 %>
            <hr>
            <% @rooms.each do |room| %>
              <div class="card p-5 ">
                <h3 class="display-6 fw-thin text-decoration-n "><%= link_to room.name.capitalize, room%> - <small class="text-danger "><%= pluralize(room.messages.count, 'message' )%></small>
                </div>
                <br>
              <% end %>
              <hr>
            </div>
          <% else %>
            <div class="card p-5">
              <h3 class="text-muted"> <i class="bi bi-bug"></i> No Rooms Found! Add a <a href="/rooms/new">Room</a> to display!</h3>
            </div>
          <% end %>
        </div>
        <div class="link mt-3">
          <%= link_to "New room", new_room_path, class: 'btn btn-primary btn-lg ' %>
        </div>
      </div>
    </div>
  </div>

app/views/rooms/new.html.erb
<div class="container mt-5">
  <div class="card p-4">
    <h1>New room</h1>
    <%= render "form", room: @room %>
    <br>
    <div>
      <%= link_to "Back to rooms", rooms_path %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="p-3">
  <%= render @room %>
</div>